{% set name = "crowdin-cli" %}
{% set version = "4.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/crowdin/{{ name }}/archive/{{ version }}.tar.gz
  sha256: 506ca1402e9e61dc94f4009c67a709be4afdc5bf05bdd82325ca829a7b281d2d

build:
  noarch: generic
  number: 0

requirements:
  build:
    - openjdk =21
    - sed
  run:
    - openjdk

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/crowdin/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: A command-line client for the Crowdin API
  dev_url: https://github.com/crowdin/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
