context:
  version: "5.0.0-next.4"

package:
  name: crowdin-cli
  version: ${{ version }}

source:
  url: https://github.com/crowdin/crowdin-cli/archive/${{ version }}.tar.gz
  sha256: a5391798b39a77a89939ee9d80fa492d73b7b1fdb9a080fc1cc21b84ded9be0b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =21
    - sed
  run:
    - openjdk

tests:
  - script:
      - crowdin-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: A command-line client for the Crowdin API
  homepage: https://github.com/crowdin/crowdin-cli
  repository: https://github.com/crowdin/crowdin-cli

extra:
  recipe-maintainers:
    - danielnachun
