context:
  version: "4.8.0"

package:
  name: crowdin-cli
  version: ${{ version }}

source:
  url: https://github.com/crowdin/crowdin-cli/archive/${{ version }}.tar.gz
  sha256: e7d8934107f10c09edb3db34ec9892942c2d136580e9fcc68d17077caf450a05

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =21
    - sed
  run:
    - openjdk

tests:
  - script:
      - crowdin-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: A command-line client for the Crowdin API
  homepage: https://github.com/crowdin/crowdin-cli
  repository: https://github.com/crowdin/crowdin-cli

extra:
  recipe-maintainers:
    - danielnachun
