context:
  version: "4.14.1"

package:
  name: crowdin-cli
  version: ${{ version }}

source:
  url: https://github.com/crowdin/crowdin-cli/archive/${{ version }}.tar.gz
  sha256: 22f65f20b7c108a41eca8e3034df5d5faa00208ccfbbd0a38df516e3ddeaafd0

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =21
    - sed
  run:
    - openjdk

tests:
  - script:
      - crowdin-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: A command-line client for the Crowdin API
  homepage: https://github.com/crowdin/crowdin-cli
  repository: https://github.com/crowdin/crowdin-cli

extra:
  recipe-maintainers:
    - danielnachun
