context:
  version: "5.0.0-next.2"

package:
  name: crowdin-cli
  version: ${{ version }}

source:
  url: https://github.com/crowdin/crowdin-cli/archive/${{ version }}.tar.gz
  sha256: 684d608e5e73863a43f000d5b947c10d6a156af4ee91f889981fbe08f721ff0b

build:
  number: 0
  noarch: generic

requirements:
  build:
    - openjdk =21
    - sed
  run:
    - openjdk

tests:
  - script:
      - crowdin-cli --help

about:
  license: MIT
  license_file:
    - LICENSE
    - build/reports/dependency-license/
  summary: A command-line client for the Crowdin API
  homepage: https://github.com/crowdin/crowdin-cli
  repository: https://github.com/crowdin/crowdin-cli

extra:
  recipe-maintainers:
    - danielnachun
